[package]
name = "tiny-shop-management-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
sqlx = { version = "0.7", features = [ "runtime-tokio", "mysql" ] }
axum = "*"
tokio = { version = "*", features = ["full"] }
tower = "*"
serde_json = "*"
serde = "*"
anyhow = "*"