serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}
auth.token = "{{ .Envs.FRP_SERVER_TOKEN }}"

[[proxies]]
name = "web"
type = "tcp"
localIP = "recom"
localPort = 5000
remotePort = {{ .Envs.FRP_WEB_REMOTE_PORT }}