serverAddr = {{ .Envs.FRP_SERVER_ADDR }}
serverPort = {{ .Envs.FRP_SERVER_PORT }}

[[web]]
name = "web"
type = "http"
localIP = "recom"
localPort = 5000
remotePort = {{ .Envs.FRP_WEB_REMOTE_PORT }}
customDomains = {{ .Envs.FRP_WEB_CUSTOM_DOMAINS }}