services:
  recom:
    build: ./recom
    container_name: recom
    env_file:
      - envs/db.env
    restart: always

  frpc:
    image: snowdreamtech/frpc
    container_name: frpc
    volumes:
      - ./frpc:/frpc
    command: -c /frpc/frpc.toml
    env_file:
      - envs/frp.env
    restart: always
