FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "bigat.py"]