FROM bitnami/pytorch:2.3.1
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install faiss-cpu mysql-connector
COPY . .
ENV TRANSFORMERS_CACHE /tmp/cache
RUN mkdir -p /tmp/cache
CMD ["python", "rest.py"]